FROM python:3.8

WORKDIR /opt/

STOPSIGNAL SIGINT

ENV PYTHONPATH=/opt

ADD setup.py .
ADD sys_monitor/ sys_monitor/
ADD main.py .

RUN python setup.py install \
    && pip install -U pytest \
    && chmod +x main.py 

ENTRYPOINT ["pytest", "-s", "tests/"]
