apiVersion: v1
kind: Pod
metadata:
  name: collector
  namespace: kubemon
  labels:
    app: collector
spec:
  nodeName: projsec01
  containers:
  - name: collector
    image: vpemfh7/kubemon:latest
    imagePullPolicy: IfNotPresent
    args: ["-t", "collector", "-H", "$(POD_IP)", "-n", "5", "-p", "9822"]
    env:
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    - name: MONITOR_DOMAIN
      value: monitor
    ports:
    - name: handler
      containerPort: 80
    - name: cmd-iface
      containerPort: 9880
    - name: healthcheck
      containerPort: 9882
    - name: instances-check
      containerPort: 9883
