apiVersion: v1
kind: PersistentVolume
metadata:
  name: kubemon-volume
  namespace: kubemon
  labels:
    type: local
spec:
  # storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kubemon-volume-claim
  namespace: kubemon
spec:
  # storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
