apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kubemon-monitor
  namespace: kubemon
  labels:
    app: monitor
spec:
  selector:
    matchLabels:
      app: monitor
  template:
    metadata:
      labels:
        app: monitor
    spec:
      containers:
        - name: kubemon-monitor
          image: vpemfh7/kubemon:latest
          imagePullPolicy: IfNotPresent
          args: ["-t", "daemon", "-H", "collector"]
          securityContext:
            privileged: true
          volumeMounts:
          - name: procfs
            mountPath: /procfs
            readOnly: true
          - name: docker
            mountPath: /var/lib/docker
            readOnly: true
          - name: sys
            mountPath: /sys
            readOnly: true
          - name: docker-sock
            mountPath: /var/run/docker.sock
            readOnly: true
          - name: hostname
            mountPath: /etc/host_hostname
            readOnly: true
          ports:
            - name: http
              containerPort: 80
          envFrom:
          - configMapRef:
              name: kubemon-env
      volumes:
      - name: sys
        hostPath:
          path: /sys
          type: Directory
      - name: docker
        hostPath:
          path: /var/lib/docker
          type: Directory
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
          type: Socket
      - name: procfs
        hostPath:
          path: /proc
          type: Directory
      - name: hostname
        hostPath:
          path: /etc/hostname
          type: File